version: '3'
services:
    server:
        image: aic_server_image
        volumes:
          - {{ graphic_log }}:/game/graphic.log:rw
          - {{ server_game_config }}:/game/config.zip:ro
          - {{ server_log }}:/game/server_view.log:rw
        environment:
          - client0_id={{ client1_id }}
          - client0_token={{ client1_token }}
          - client1_id={{ client2_id }}
          - client1_token={{ client2_token }}
        deploy:
            resources:
                limits:
                    cpus: '0.7'
                    memory: '1G'
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: '1G'
    client1:
        image: aic_client_image
        volumes:
            - {{ client1_code }}:/game/client.zip:ro
        depends_on:
            - server
        environment:
            - token={{ client1_token }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
    client2:
        image: aic_client_image
        volumes:
            - {{ client2_code }}:/game/client.zip:ro
        depends_on:
            - server
        environment:
            - token={{ client2_token }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'