apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: code-compiled-zip
  name: code-compiled-zip
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      pv: code-compiled-zip
  storageClassName: slow
status: {}
